# Generated by Django 3.0.8 on 2021-09-16 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='帳號')),
                ('password', models.CharField(max_length=128, verbose_name='密碼')),
                ('type', models.CharField(choices=[('AdminUser', '管理員'), ('Member', '會員')], default='AdminUser', max_length=50, verbose_name='類型')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='超級管理員狀態')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最後登入時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '使用者',
                'verbose_name_plural': '使用者',
            },
            managers=[
                ('objects', user.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '會員',
                'verbose_name_plural': '會員',
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '管理者',
                'verbose_name_plural': '管理者',
                'db_table': 'admin_users',
            },
        ),
    ]
